name: ci

on:
  push:
  pull_request:

jobs:
  test-unix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.mod
      - name: Run checks
        run: ./scripts/check.sh

  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.mod
      - name: Run checks
        shell: powershell
        run: ./scripts/check.ps1
